### ISSUE TITLE
Make rejoining a server not reset remapped keys

### ISSUE THREAD

**Issue by Boy0000** [ASangarin/AriKeys#2] opened 2022-04-30 14:17 UTC
Currently it will reset any local change one makes to it when rejoining and therefore resend the keys
Feels like it makes the whole point kind of redundant?

Or is this intended and leaving DefaultKey in the config blank the way to do this?

**Comment by ASangarin** [comment] 2022-10-31 13:56
Unable to reproduce on latest versions.
Rejoining a server keeps your custom rebinds and even closing down the game completely still saves as it should.
Maybe a write-permission thing? AriKeys writes data the same way Minecraft writes it's options, so I'm unsure about this one.
But regardless, I've been unable to reproduce, so I will close this issue.

**Closed as completed by ASangarin** 2022-10-31 13:56 UTC
Labels: bug
